<?php

use Illuminate\Database\Seeder;

class MedicamentsTableSeeder extends Seeder
{
    public function run()
    {
        factory(\App\Medicament::class)->create(['nom_id' => 28, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 29, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 30, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 31, 'type_id' => 128]);
        factory(\App\Medicament::class)->create(['nom_id' => 32, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 33, 'type_id' => 130]);
        factory(\App\Medicament::class)->create(['nom_id' => 34, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 35, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 36, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 37, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 38, 'type_id' => 133]);
        factory(\App\Medicament::class)->create(['nom_id' => 39, 'type_id' => 134]);
        factory(\App\Medicament::class)->create(['nom_id' => 40, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 41, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 42, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 43, 'type_id' => 135]);
        factory(\App\Medicament::class)->create(['nom_id' => 44, 'type_id' => 136]);
        factory(\App\Medicament::class)->create(['nom_id' => 45, 'type_id' => 137]);
        factory(\App\Medicament::class)->create(['nom_id' => 46, 'type_id' => 138]);
        factory(\App\Medicament::class)->create(['nom_id' => 47, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 48, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 49, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 50, 'type_id' => 138]);
        factory(\App\Medicament::class)->create(['nom_id' => 51, 'type_id' => 134]);
        factory(\App\Medicament::class)->create(['nom_id' => 52, 'type_id' => 130]);
        factory(\App\Medicament::class)->create(['nom_id' => 53, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 54, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 55, 'type_id' => 139]);
        factory(\App\Medicament::class)->create(['nom_id' => 56, 'type_id' => 137]);
        factory(\App\Medicament::class)->create(['nom_id' => 57, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 58, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 59, 'type_id' => 137]);
        factory(\App\Medicament::class)->create(['nom_id' => 60, 'type_id' => 139]);
        factory(\App\Medicament::class)->create(['nom_id' => 61, 'type_id' => 134]);
        factory(\App\Medicament::class)->create(['nom_id' => 62, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 63, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 64, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 65, 'type_id' => 140]);
        factory(\App\Medicament::class)->create(['nom_id' => 66, 'type_id' => 135]);
        factory(\App\Medicament::class)->create(['nom_id' => 67, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 68, 'type_id' => 141]);
        factory(\App\Medicament::class)->create(['nom_id' => 69, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 70, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 71, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 72, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 73, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 75, 'type_id' => 136]);
        factory(\App\Medicament::class)->create(['nom_id' => 76, 'type_id' => 133]);
        factory(\App\Medicament::class)->create(['nom_id' => 77, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 78, 'type_id' => 136]);
        factory(\App\Medicament::class)->create(['nom_id' => 79, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 80, 'type_id' => 130]);
        factory(\App\Medicament::class)->create(['nom_id' => 81, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 82, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 83, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 84, 'type_id' => 135]);
        factory(\App\Medicament::class)->create(['nom_id' => 85, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 86, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 88, 'type_id' => 133]);
        factory(\App\Medicament::class)->create(['nom_id' => 89, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 90, 'type_id' => 135]);
        factory(\App\Medicament::class)->create(['nom_id' => 91, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 92, 'type_id' => 139]);
        factory(\App\Medicament::class)->create(['nom_id' => 93, 'type_id' => 134]);
        factory(\App\Medicament::class)->create(['nom_id' => 94, 'type_id' => 139]);
        factory(\App\Medicament::class)->create(['nom_id' => 96, 'type_id' => 136]);
        factory(\App\Medicament::class)->create(['nom_id' => 97, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 98, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 99, 'type_id' => 138]);
        factory(\App\Medicament::class)->create(['nom_id' => 100, 'type_id' => 135]);
        factory(\App\Medicament::class)->create(['nom_id' => 101, 'type_id' => 132]);
        factory(\App\Medicament::class)->create(['nom_id' => 102, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 103, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 104, 'type_id' => 140]);
        factory(\App\Medicament::class)->create(['nom_id' => 106, 'type_id' => 142]);
        factory(\App\Medicament::class)->create(['nom_id' => 107, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 108, 'type_id' => 142]);
        factory(\App\Medicament::class)->create(['nom_id' => 109, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 110, 'type_id' => 143]);
        factory(\App\Medicament::class)->create(['nom_id' => 111, 'type_id' => 140]);
        factory(\App\Medicament::class)->create(['nom_id' => 112, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 113, 'type_id' => 138]);
        factory(\App\Medicament::class)->create(['nom_id' => 114, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 115, 'type_id' => 138]);
        factory(\App\Medicament::class)->create(['nom_id' => 116, 'type_id' => 136]);
        factory(\App\Medicament::class)->create(['nom_id' => 117, 'type_id' => 134]);
        factory(\App\Medicament::class)->create(['nom_id' => 118, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 119, 'type_id' => 137]);
        factory(\App\Medicament::class)->create(['nom_id' => 120, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 121, 'type_id' => 144]);
        factory(\App\Medicament::class)->create(['nom_id' => 122, 'type_id' => 129]);
        factory(\App\Medicament::class)->create(['nom_id' => 123, 'type_id' => 131]);
        factory(\App\Medicament::class)->create(['nom_id' => 124, 'type_id' => 127]);
        factory(\App\Medicament::class)->create(['nom_id' => 125, 'type_id' => 134]);
        factory(\App\Medicament::class)->create(['nom_id' => 126, 'type_id' => 132]);
    }
}
